# Generated by Django 4.0.5 on 2022-07-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='clinet_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
