# Generated by Django 4.0.5 on 2022-07-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_orderitem_order_orderitem_clinet_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='clinet_id',
            new_name='client_id',
        ),
    ]
