# Generated by Django 4.0.5 on 2022-07-19 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_clinet_id_orderitem_client_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
