# Generated by Django 4.0.5 on 2022-07-27 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_orderitem_product_id_alter_orderitem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='complete',
        ),
    ]
